// Create a Users
POST http://localhost:5000/pemilik-kost
Content-Type: application/json

{
    "name": "lala",
    "email": "lala@gmail.com",
    "password": "123",
    "confPassword": "123",
    "role": "Pemilik Kost"
}

###
// get All Users
GET http://localhost:5000/pemilik-kost

###
// get Single User
GET http://localhost:5000/pemilik-kost/21f3ddeb-34f7-4f91-8196-7d917056aad8

###
// update a User
PATCH  http://localhost:5000/pemilik-kost/0e8c6821-f954-40ce-81e7-b386e413cbd9
Content-Type: application/json

{
    "name": "lala up",
    "email": "levi@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
// delete a user
DELETE  http://localhost:5000/pemilik-kost/0e8c6821-f954-40ce-81e7-b386e413cbd9